# Generated by Django 2.2.5 on 2019-10-07 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('office_hours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='officehour',
            name='checkin_time',
            field=models.TimeField(auto_now_add=True, null=True, verbose_name='Hora do check-in'),
        ),
        migrations.AddField(
            model_name='officehour',
            name='checkout_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora do check-out'),
        ),
        migrations.AddField(
            model_name='officehour',
            name='date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Dia'),
        ),
        migrations.AddField(
            model_name='officehour',
            name='duration',
            field=models.DurationField(blank=True, null=True, verbose_name='Duração'),
        ),
        migrations.AddField(
            model_name='officehour',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Membro'),
        ),
    ]
