# Generated by Django 2.2.5 on 2019-10-07 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('office_hours', '0002_auto_20191007_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officehour',
            name='checkin_time',
            field=models.TimeField(auto_now_add=True, verbose_name='Hora do check-in'),
        ),
        migrations.AlterField(
            model_name='officehour',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Dia'),
        ),
        migrations.AlterField(
            model_name='officehour',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Membro'),
        ),
    ]
