# Generated by Django 2.2.5 on 2019-10-10 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_hours', '0007_auto_20191008_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officehour',
            name='duration',
            field=models.DurationField(blank=True, help_text='[DD] [HH:[MM:]] format', null=True, verbose_name='Duração'),
        ),
    ]
