# Generated by Django 2.2.6 on 2019-10-31 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_hours', '0008_auto_20191009_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officehour',
            name='duration',
            field=models.DurationField(blank=True, help_text='[HH:[MM:] format', null=True, verbose_name='Duração'),
        ),
    ]
