# Generated by Django 2.2.6 on 2019-11-13 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office_hours', '0009_auto_20191031_0921'),
        ('office_hours', '0009_auto_20191106_2321'),
    ]

    operations = [
    ]
