# Generated by Django 2.2.5 on 2019-10-10 00:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('REB', 'REB'), ('RA', 'Reunião de Área'), ('RT', 'Reunião de Time'), ('LR', 'Reunião de LR'), ('CN', 'Reunião de Corner')], max_length=3, null=True, verbose_name='Tipo da Reunião')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Dia')),
                ('time', models.TimeField(default=django.utils.timezone.now, verbose_name='Hora do check-in')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Líder')),
            ],
        ),
    ]
