# Generated by Django 2.2.6 on 2019-10-24 01:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_meeting_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Hora'),
        ),
    ]
