# Generated by Django 2.2.6 on 2019-10-24 02:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0005_auto_20191023_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='participations',
        ),
        migrations.AddField(
            model_name='participation',
            name='meeting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='meetings.Meeting', verbose_name='Reunião'),
        ),
        migrations.AlterField(
            model_name='participation',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Participante'),
        ),
    ]
