# Generated by Django 2.2.5 on 2019-09-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='department',
            field=models.CharField(blank=True, choices=[('LCP', 'LCP'), ('PM', 'PM'), ('F&L', 'F&L'), ('B2C', 'B2C'), ('B2B', 'B2B'), ('OGE', 'OGE'), ('OGT', 'OGT'), ('OGV', 'OGV'), ('IGE', 'IGE'), ('IGT', 'IGT')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='post',
            field=models.CharField(blank=True, choices=[('LCP', 'LCP'), ('LCVP', 'LCVP'), ('TLB', 'TLB'), ('Membro', 'Membro')], max_length=2, null=True),
        ),
    ]
