# Generated by Django 2.2.5 on 2019-09-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='department',
            field=models.CharField(blank=True, choices=[('1', 'LCP'), ('2', 'PM'), ('3', 'F&L'), ('4', 'B2C'), ('5', 'B2B'), ('6', 'OGE'), ('7', 'OGT'), ('8', 'OGV'), ('9', 'IGE'), ('10', 'IGT')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='post',
            field=models.CharField(blank=True, choices=[('1,', 'LCP'), ('2', 'LCVP'), ('3', 'TLB'), ('4', 'Membro')], max_length=2, null=True),
        ),
    ]
