# Generated by Django 2.2.5 on 2019-09-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20190929_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='podio_code',
            field=models.CharField(max_length=10, unique=True, verbose_name='ID do Podio'),
        ),
    ]
