# Generated by Django 2.2.6 on 2019-11-07 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_auto_20191106_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='post',
            field=models.CharField(blank=True, choices=[('lcp', 'LCP'), ('lcvp', 'LCVP'), ('tlb', 'TLB'), ('membro', 'Membro')], max_length=2, null=True, verbose_name='Cargo'),
        ),
    ]
