# Generated by Django 2.2.6 on 2019-11-07 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_auto_20191106_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='department',
            field=models.CharField(blank=True, choices=[('lcp', 'LCP'), ('pm', 'PM'), ('f&l', 'F&L'), ('b2c', 'B2C'), ('b2b', 'B2B'), ('oge', 'OGE'), ('ogt', 'OGT'), ('ogv', 'OGV'), ('ige', 'IGE'), ('igt', 'IGT')], max_length=10, null=True, verbose_name='Área'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='post',
            field=models.CharField(blank=True, choices=[('lcp', 'LCP'), ('lcvp', 'LCVP'), ('tlb', 'TLB'), ('membro', 'Membro')], max_length=10, null=True, verbose_name='Cargo'),
        ),
    ]
